<?

// function ish_drupal_module_form_user_register_form_alter(&$form, $form_state, $form_id) {
//   // $form['account']['name']['#title'] = t('First and last name');
//   // $form['account']['name']['#description'] = t("Rewrite this about spaces, periods (.), hyphens (-) and apostrophes (').");
//
//   // $markup = '<div id="my-custom-markup"><h1>Here is my markup</h1></div>';
//   // $form['field_mycustommarkup'] = [
//   //     '#type' => 'markup',
//   //     '#markup' => $markup,
//   //     '#weight' => 1,
//   // ];
//
//   // $markup = '<div id="my-custom-markup"><h1>New 222 Recaptcha</h1></div>';
//   // $form['field_mycustommarkup'] = [
//   //     '#type' => 'markup',
//   //     '#markup' => $markup,
//   //     '#weight' => 10,
//   // ];
//
//   // $form['#submit'][] = 'ish_drupal_module_2_submit';
// }

// function ish_drupal_module_2_submit($form_id, $form_values) {
//   drupal_set_message(t('Submit Function Executed!'));
//   var_dump("And this, the form has been submitted.");
//   var_dump( $form_id );
//   var_dump( $form_values );
//   exit(0);
// }

/**
 * Implements hook_theme().
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 *
 * If you change this method, clear theme registry and routing
 * table 'drush cc theme-registry' and 'drush cc router'.
**/
function ish_drupal_module_theme($existing, $type, $theme, $path) {

  return [
    'ish_users_edit' => [
      'template' => 'edit',
      'path' => $path . '/templates/users',
      'variables' => [
      ],
    ],
    'ish_locations_show' => [
      'render element' => 'requirements',
      'template' => 'show',
      'path' => $path . '/templates/locations',
      'variables' => [
        'location' => NULL,
        // 'request' => NULL,
      ],
    ],
  ];

}
