#!/bin/bash

# set -e ## error
set -x

yarn run build

git add .
git commit -m 'autocommit'
git push

ssh do2 "cd /mnt/volume_sfo2_01/projects/docker/volumes/wco_drupal_production_data/web/modules/ish_drupal_module ; git pull && echo $HOSTNAME ok"


set +e
set +x
echo ok
